name: Node.js Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
      - run: npm ci
      - run: npm run build:es
      - run: npm run build:commonjs

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:es
      - run: npm run build:commonjs
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
